//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinproService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        public int ItemId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string ClothDescription { get; set; }
        public byte[] ProductImageUrl { get; set; }
    }
}
